### ISSUE TITLE
Checkout Display

### ISSUE THREAD

**Issue by ryconnolly** [slideloft/stellarwoocommerce-plugin#3]
On checkout can the stellar logo be added? (Would help for people not familiar with stellar recognize it on an exchange).
Also, I have 3 pane checkout so the Wallet ID runs off the page.  Any thought on a solution for that? 
(I guess wrap it, or scrollable box or something).
https://puu.sh/zaseO/fd88d73e56.png

**Comment by slideloft** [comment]
New version sorts out this issue
